// import 'datatables.net'
// import 'datatables.net-bs'
// import 'datatables'

import 'modules/admin-lte/plugins/jQueryUI/jquery-ui.min'
import 'modules/admin-lte/plugins/jQuery/jquery-2.2.3.min'
import 'modules/jquery/dist/jquery.min'
import 'modules/admin-lte/plugins/fastclick/fastclick'
import 'modules/admin-lte/plugins/slimScroll/jquery.slimscroll.min'
import 'modules/admin-lte/dist/js/app.min'
import 'modules/admin-lte/plugins/fullcalendar/fullcalendar.min'
import 'modules/admin-lte/plugins/input-mask/jquery.inputmask'
import 'modules/admin-lte/plugins/input-mask/jquery.inputmask.date.extensions'
import 'modules/admin-lte/plugins/input-mask/jquery.inputmask.extensions'
import 'modules/admin-lte/plugins/daterangepicker/daterangepicker'
import 'modules/admin-lte/plugins/daterangepicker/moment.min'
import 'modules/admin-lte/plugins/datepicker/bootstrap-datepicker'
import 'modules/admin-lte/plugins/colorpicker/bootstrap-colorpicker.min'
import 'modules/admin-lte/plugins/timepicker/bootstrap-timepicker.min'
import 'modules/admin-lte/plugins/iCheck/icheck.min'
import 'modules/admin-lte/plugins/select2/select2.full.min'
import 'modules/admin-lte/plugins/datatables/jquery.dataTables.min'
import 'modules/admin-lte/plugins/bootstrap-slider/bootstrap-slider'
import 'modules/admin-lte/bootstrap/js/bootstrap.min'
import 'modules/admin-lte/dist/js/demo'
import 'modules/moment/moment'


// import 'modules/admin-lte/plugins/flot/jquery.flot.min'
// import 'modules/admin-lte/plugins/flot/jquery.flot.resize.min'
// import 'modules/admin-lte/plugins/flot/jquery.flot.pie.min'
// import 'modules/admin-lte/plugins/flot/jquery.flot.categories.min'
// import 'modules/admin-lte/plugins/flot/jquery.flot'
// import 'modules/admin-lte/plugins/flot/jquery.flot.resize'
// import 'modules/admin-lte/plugins/flot/jquery.flot.pie.min'
// import 'modules/admin-lte/plugins/flot/jquery.flot.categories'
import 'modules/admin-lte/plugins/colorpicker/bootstrap-colorpicker.min.css'
import 'modules/admin-lte/plugins/select2/select2.min.css'
import 'modules/admin-lte/plugins/timepicker/bootstrap-timepicker.min.css'
import 'modules/admin-lte/plugins/iCheck/all.css'
import 'modules/admin-lte/plugins/datepicker/datepicker3.css'
import 'modules/admin-lte/plugins/daterangepicker/daterangepicker.css'
import 'modules/font-awesome/css/font-awesome.min.css'
import 'modules/ionicons/dist/css/ionicons.min.css'
import 'modules/admin-lte/bootstrap/css/bootstrap.min.css'
import 'modules/admin-lte/dist/css/AdminLTE.min.css'
import 'modules/admin-lte/dist/css/skins/_all-skins.min.css'
import 'modules/admin-lte/plugins/iCheck/flat/blue.css'
import 'modules/admin-lte/plugins/fullcalendar/fullcalendar.min.css'
import 'modules/admin-lte/plugins/fullcalendar/fullcalendar.print.css'
// import 'modules/normalize.css/normalize.css'
// import 'modules/@blueprintjs/icons/lib/css/blueprint-icons.css'
// import 'modules/@blueprintjs/core/lib/css/blueprint.css'

import 'modules/admin-lte/plugins/datatables/jquery.dataTables.min.css'
import 'modules/admin-lte/plugins/datatables/jquery.dataTables_themeroller.css'
import 'modules/admin-lte/plugins/datatables/dataTables.bootstrap.css'
// import 'modules/admin-lte/plugins/datatables/dataTables.bootstrap.min'

import 'modules/admin-lte/plugins/datatables/jquery.dataTables.css'

import './custom.css'
import './custom.min.css'